---
- hosts: localhost
  connection: local
  tasks:
  - name: dick_usage_check
    sensu_check:
      name: disk_usage_check
      command: /opt/sensu/embedded/bin/check-disk-usage.rb -w 20 -c 90 
      subscribers: dev
      handlers: st2
      interval: 60
  - name: check_cpu
    sensu_check:
      name: check_cpu
      command: /opt/sensu/embedded/bin/check-cpu.rb -w 20 -c 80 
      subscribers: dev
      interval: 60
  - name: check_load
    sensu_check:
      name: check_load
      command: /opt/sensu/embedded/bin/check-load.rb -w L1,L5,L15
      subscribers: dev
      interval: 60
  - name: check_containers
    sensu_check:
      name: check_containers
      command: /opt/sensu/embedded/bin/check-container.rb -N portainer
      subscribers: dev
      interval: 60   
  - name: check_ports
    sensu_check:
      name: check_ports
      command: /opt/sensu/embedded/bin/check-ports.rb -p 22,8080
      subscribers: dev
      interval: 60
  - name: check_domain
    sensu_check:
      name: check_domain
      command: /opt/sensu/embedded/bin/check-whois-domain-expiration.rb -d  myhcl.com 
      subscribers: dev
      interval: 60
  - name: check_container_logs
    sensu_check:
      name: check_container_logs
      command: /opt/sensu/embedded/bin/check-container-logs.rb
      subscribers: dev
      interval: 60
  - name: check_docker_container
    sensu_check:
      name: check_docker_containers
      command: /opt/sensu/embedded/bin/check-docker-container.rb -w 0
      subscribers: dev
      interval: 60
  - name: check_redis_mem
    sensu_check:
      name: check_redis_mem
      command: /opt/sensu/embedded/bin/check-redis-memory-percentage.rb -h localhost -p 6379  -w 20 -c 90
      subscribers: dev
      interval: 60

  - name: ec2-cpu_balance
    sensu_check:
      name: ec2-cpu_balance
      command: /opt/sensu/embedded/bin/check-ec2-cpu_balance.rb -r us-west-2 -t Sensu -c 50
      subscribers: dev
      handlers: slack
      interval: 60
  - name: restart services
    systemd: name={{ item }}  state=restarted
    with_items:
      - sensu-server
      - sensu-api
      - sensu-client
      - uchiwa

